- name: play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

# play level variables are access from all tasks and  from files also

- name: file level variable
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}

# task level variable

- name: task level variable
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
      vars:
        URL: hosts.example.com

