- name: play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

# play level variables are access from all tasks and  from files also

- name: file level variable
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}

# task level variable

- name: task level variable
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
      vars:
        URL: hosts.example.com

# inventory level variable

- name: inventory level variable
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}
# ip address and dns name

- name: IP address
  hosts: all
  tasks:
    - name: print IP address
      ansible.builtin.debug:
        msg: Architecture = {{ansible_architecture}}, IP address = {{ansible_eth0.ipv4.address}}

 # ansible runtime variables

- name: Register variable
  hosts: all
  tasks:
    - name: Run shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Print output of shell command
      ansible.builtin.debug:
        msg: {{"OUT"}}



